import assert from 'node:assert/strict';import worker from '../dist/server/index.js';import {appModules,routeForURL} from '../dist/app-routes.js';
const origin='https://site.example',user={'oai-authenticated-user-id':'account-a'},owner={...user,'oai-authenticated-user-email':'owner@example.com'},env={JARVIS_OWNER_EMAIL:'owner@example.com'};
for(const path of ['/education.html','/website-editor.html']){assert.equal((await worker.fetch(new Request(origin+path),env)).status,302);assert.equal((await worker.fetch(new Request(origin+path,{headers:user}),env)).status,200);}
for(const path of ['/api/education/workspace','/api/builder/projects']){assert.equal((await worker.fetch(new Request(origin+path),env)).status,401);assert.equal((await worker.fetch(new Request(origin+path,{headers:user}),env)).status,503);}
for(const path of ['/education.js','/website-editor.js','/vendor/grapesjs/grapes.min.js','/vendor/grapesjs/grapes.min.css','/vendor/grapesjs/LICENSE.txt'])assert.equal((await worker.fetch(new Request(origin+path),env)).status,200,path);
for(const path of ['/project-sources/merge-manifest.json','/project-sources/github/creative-studio/command_engine.py','/project-sources/library/Pasted text.txt'])assert.equal((await worker.fetch(new Request(origin+path),env)).status,404,'Original source is not public content');
const response=await worker.fetch(new Request(origin+'/api/platform/alignment',{headers:owner}),env);assert.equal(response.status,200);const data=await response.json();assert.equal(data.sourceMerge.files.length,220);assert.equal(data.sourceMerge.coderabbit.localReview,'not_run');assert.equal(data.sourceMerge.builderRepositories[0].state,'installed');
assert.ok(appModules.find(m=>m.id==='education'&&m.group==='business'));assert.ok(appModules.find(m=>m.id==='visual-website-editor'&&m.group==='website'));assert.equal(routeForURL('/education.html'),'education');assert.equal(routeForURL('/website-editor.html'),'visual-website-editor');
console.log('PASS deployed Worker routing, sign-in gates, local editor assets, private source boundaries and existing app module integration');
