import assert from 'node:assert/strict';
import {build} from 'esbuild';
const built=await build({stdin:{contents:"export {zuxuruBackend} from './handler.mjs'; export {withZuxuruContext,currentContext} from './context.mjs'; export {save,get,list} from './zuxuru.ts'; export {businessIntelligence,prioritize} from './intelligence-view.ts'; export {normalizeAI} from './ai-engine.ts';",resolveDir:process.cwd()+'/worker/zuxuru',loader:'ts'},bundle:true,platform:'node',format:'esm',write:false});
const {zuxuruBackend,withZuxuruContext,currentContext,save,get,list,businessIntelligence,prioritize,normalizeAI}=await import('data:text/javascript;base64,'+Buffer.from(built.outputFiles[0].text).toString('base64'));
const rows=new Map();
const DB={prepare(sql){let args;assert.ok(!/\b(?:FROM|INTO|UPDATE)\s+records\b/i.test(sql),'Namespaced storage required');return {bind(...v){args=v;return this},async run(){if(sql.startsWith('INSERT')){let [id,owner,kind,data,created_at,updated_at]=args;rows.set(id,{id,owner,kind,data,created_at,updated_at});return {meta:{changes:1}};}if(sql.startsWith('UPDATE')){let [data,updated_at,id,owner,kind]=args;let r=rows.get(id);if(r?.owner===owner&&r.kind===kind)rows.set(id,{...r,data,updated_at});}if(sql.startsWith('DELETE')){let [id,owner,kind]=args;let r=rows.get(id);if(r?.owner===owner&&r.kind===kind)rows.delete(id);}return {meta:{changes:1}}},async first(){let [id,owner,kind]=args;let r=rows.get(id);return r?.owner===owner&&r.kind===kind?r:null},async all(){let [owner,kind]=args;return {results:[...rows.values()].filter(r=>r.owner===owner&&r.kind===kind)}}}}};
const media={get:async()=>null,delete:async()=>{},put:async()=>{}},env={DB,MEDIA:media,JARVIS_OWNER_EMAIL:'ceo@example.com',JARVIS_VAULT_KEY:'ab'.repeat(32)};
const req=(user,method='GET',body,origin='https://example.com',email='customer@example.com')=>new Request('https://example.com/api/zuxuru/os',{method,headers:{...(user?{'oai-authenticated-user-id':user,'oai-authenticated-user-email':email}:{}),origin,'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
assert.equal((await zuxuruBackend(req(null),env)).status,401);
assert.equal((await zuxuruBackend(req('a','PUT'),env)).status,405);
assert.equal((await zuxuruBackend(req('a','POST',{action:'lead_save',name:'bad'},'https://other.example'),env)).status,403);
assert.equal(rows.size,0);
const lead=await (await zuxuruBackend(req('a','POST',{action:'lead_save',name:'Real saved lead'}),env)).json();
assert.ok(lead.result.id);
assert.equal((await (await zuxuruBackend(req('b'),env)).json()).lead.length,0);
assert.equal((await (await zuxuruBackend(req('a'),env)).json()).lead.length,1);
const blocked=await zuxuruBackend(req('b','POST',{action:'lead_stage',id:lead.result.id,stage:'Won'}),env);assert.equal(blocked.status,400);
assert.equal((await zuxuruBackend(req('a','POST',{action:'github_repositories'}),env)).status,403);
const missingConsent=await (await zuxuruBackend(req('a','POST',{action:'ai_analyze',consent:false}),env)).json();assert.match(missingConsent.error,/Approve sending/);
let release;const gate=new Promise(r=>release=r);
const a=withZuxuruContext(req('a'),env,async()=>{await gate;assert.equal(currentContext().user.userId,'a');assert.equal(currentContext().env.BUCKET,media);assert.equal(Buffer.from(currentContext().env.SEARCH_VAULT_KEY,'base64').toString('hex'),env.JARVIS_VAULT_KEY);});
await withZuxuruContext(req('b'),{...env,MEDIA:{label:'other'}},async()=>{assert.equal(currentContext().user.userId,'b');release();await a;assert.equal(currentContext().user.userId,'b');});
assert.throws(()=>currentContext(),/unavailable/);
const p=await withZuxuruContext(req('a'),env,()=>save('a','profile',{name:'Fixture',identityConfirmed:true,selectedEvidenceId:'proof',selectedSourceUrl:'https://business.example/',investigatedAt:new Date().toISOString(),evidence:[{id:'proof',url:'https://business.example/',state:'Retrieved',platform:'Website'}],score:{value:25,sourceUrl:'https://business.example/',checks:[{name:'Public contact',observed:false,points:25}]}}));
const intel=await (await zuxuruBackend(req('a','POST',{action:'intelligence_analyze',id:p.id}),env)).json();assert.equal(intel.result.score.value,25);assert.equal(intel.result.opportunities[0].priority,17.5);
assert.equal(prioritize(5,.7,5,1),17.5);
const analyzed=normalizeAI({summary:'Draft',recommendations:[{title:'Draft',reason:'Review',evidenceIds:['fake','proof']}]},p.evidence);assert.deepEqual(analyzed.recommendations[0].evidenceIds,['proof']);assert.equal(analyzed.score,null);
assert.equal(businessIntelligence({...p,identityConfirmed:false}).score,null);
assert.equal((await (await zuxuruBackend(req('b','POST',{action:'intelligence_analyze',id:p.id}),env)).json()).result,undefined);
assert.equal((await (await zuxuruBackend(req('a'),env)).json()).ai.configured,false);
assert.equal((await (await zuxuruBackend(req('a'),env)).json()).postiz.configured,false);
console.log('PASS Zuxuru merge: bundled backend, shared auth/storage, cross-owner isolation, request-context concurrency, origins, CEO permissions, consent, evidence scoring and citation validation. No live provider requests.');
